#ifndef QUESTION_BANK_H
#define QUESTION_BANK_H

typedef struct {
    const char *question;
    const char *options[4];
    int answer;
    const char *hint;
} QuizQuestion;

#define QQ(q, a, b, c, d, ans, hint) {q, {a, b, c, d}, ans, hint}

static const QuizQuestion QUIZ_EASY_QUESTIONS[] = {
    QQ("Em C, qual funcao gera numeros pseudoaleatorios?", "printf", "rand", "fgets", "sqrt", 2, "Ela esta em stdlib.h."),
    QQ("Qual funcao abre um arquivo em C?", "fopen", "scanf", "malloc", "pow", 1, "Ela comeca com a letra f."),
    QQ("Qual estrutura repete comandos enquanto a condicao for verdadeira?", "if", "struct", "while", "typedef", 3, "E um laco."),
    QQ("Qual valor representa verdadeiro em C quando usamos int?", "0", "Qualquer valor diferente de 0", "Apenas -1", "Apenas 100", 2, "Zero representa falso."),
    QQ("Qual operador testa igualdade em C?", "=", "==", "!=", ">=", 2, "Nao confunda com atribuicao."),
    QQ("Qual tipo costuma armazenar uma letra?", "double", "char", "long", "void", 2, "Tem 4 letras."),
    QQ("Qual funcao le uma linha inteira com mais seguranca?", "gets", "puts", "fgets", "atof", 3, "Ela recebe o tamanho do buffer."),
    QQ("Em C, o operador % devolve o que?", "Potencia", "Resto da divisao", "Raiz", "Media", 2, "Pense em 7 % 3."),
    QQ("Para que serve #include?", "Encerrar o programa", "Importar cabecalhos", "Declarar variavel", "Apagar memoria", 2, "Usamos com stdio.h."),
    QQ("Qual laco costuma ser usado quando sabemos o contador?", "for", "switch", "goto", "typedef", 1, "Ele tem inicio, condicao e passo."),
    QQ("Qual e o tipo de retorno padrao de main?", "char", "float", "int", "void*", 3, "Normalmente devolve 0 no fim."),
    QQ("Qual operador logico significa E?", "||", "&&", "!", "%", 2, "Os dois precisam ser verdadeiros."),
    QQ("Qual operador logico significa OU?", "||", "&&", "!", "&", 1, "Basta uma condicao verdadeira."),
    QQ("Qual operador logico nega uma condicao?", "!", "~", "^", "%", 1, "Transforma verdadeiro em falso."),
    QQ("O que ++ faz com uma variavel inteira?", "Divide por 2", "Incrementa em 1", "Troca o sinal", "Zera a variavel", 2, "x++ altera x para cima."),
    QQ("Qual simbolo acessa um elemento de vetor?", "()", "{}", "[]", "<>", 3, "Exemplo: v[3]."),
    QQ("Um ponteiro armazena o que?", "Um texto", "Um endereco de memoria", "Uma matriz", "Uma funcao pronta", 2, "Ele aponta para algo."),
    QQ("Qual especificador de formato imprime int com printf?", "%f", "%s", "%d", "%c", 3, "Nao e o de float."),
    QQ("Qual comando sai imediatamente de um laco?", "continue", "break", "return 1.0", "sizeof", 2, "Ele interrompe o loop."),
    QQ("Qual comando pula para a proxima iteracao do laco?", "goto", "exit", "continue", "union", 3, "Ele nao encerra o loop."),
    QQ("Qual estrutura escolhe entre dois blocos com base numa condicao?", "if/else", "enum", "struct", "register", 1, "Um bloco e alternativo."),
    QQ("O que sizeof costuma retornar?", "Um ponteiro", "A quantidade de bytes", "Um texto", "Um endereco", 2, "Serve para medir memoria."),
    QQ("Qual constante costuma representar ponteiro nulo?", "EOF", "NULL", "stdin", "RAND_MAX", 2, "Indica ausencia de endereco valido."),
    QQ("Qual biblioteca tem printf e scanf?", "math.h", "time.h", "stdio.h", "ctype.h", 3, "E a biblioteca padrao de entrada e saida."),
    QQ("O que return faz dentro de uma funcao?", "Repete a funcao", "Sai da funcao e devolve um valor", "Cria um ponteiro", "Ordena vetor", 2, "Ele encerra a execucao da funcao."),

    QQ("Se x + 7 = 12, quanto vale x?", "3", "4", "5", "6", 3, "Isole x."),
    QQ("Se 2x = 18, quanto vale x?", "7", "8", "9", "10", 3, "Divida ambos os lados por 2."),
    QQ("Resolva: 3x - 5 = 10.", "3", "4", "5", "6", 2, "Primeiro some 5."),
    QQ("Se x/4 = 6, quanto vale x?", "18", "20", "24", "28", 3, "Multiplique por 4."),
    QQ("Resolva: 2x + 3 = 11.", "2", "3", "4", "5", 3, "Subtraia 3 e depois divida por 2."),
    QQ("Qual e a solucao de x + 2 > 5?", "x > 3", "x < 3", "x = 3", "x >= 2", 1, "Isole x na inequacao."),
    QQ("Qual e a solucao de 2x <= 10?", "x <= 10", "x <= 5", "x >= 5", "x >= 10", 2, "Divida por 2."),
    QQ("Se f(x) = 2x + 1, qual e f(3)?", "5", "6", "7", "8", 3, "Substitua x por 3."),
    QQ("Se f(x) = x - 4, qual e a raiz da funcao?", "2", "3", "4", "5", 3, "A raiz faz f(x)=0."),
    QQ("Quanto e 20% de 50?", "5", "10", "15", "20", 2, "Pense em um quinto."),
    QQ("A media aritmetica de 4, 6 e 8 e:", "5", "6", "7", "8", 2, "Some e divida por 3."),
    QQ("Se y = 3x, quanto vale y quando x = 4?", "7", "10", "12", "14", 3, "Substitua x."),
    QQ("Quanto vale 5^2?", "10", "20", "25", "30", 3, "Cinco ao quadrado."),
    QQ("Quanto vale a raiz quadrada de 81?", "7", "8", "9", "10", 3, "Um quadrado perfeito."),
    QQ("Se 7 + 8 = 15, qual e o dobro desse resultado?", "20", "24", "30", "32", 3, "Multiplique 15 por 2."),
    QQ("A area de um retangulo de base 5 e altura 3 e:", "8", "12", "15", "18", 3, "Base vezes altura."),
    QQ("O perimetro de um quadrado de lado 4 e:", "8", "12", "16", "20", 3, "Sao quatro lados iguais."),
    QQ("Se 3/4 de um numero e 12, o numero e:", "14", "15", "16", "18", 3, "Multiplique 12 por 4/3."),
    QQ("A funcao y = x + 2 e de qual tipo?", "Quadratica", "Linear", "Exponencial", "Trigonometrica", 2, "O maior expoente de x e 1."),
    QQ("Se x - 9 = -2, quanto vale x?", "5", "6", "7", "8", 3, "Some 9 aos dois lados."),
    QQ("Quanto e 30% de 200?", "40", "50", "60", "70", 3, "Tres decimos de 200."),
    QQ("Se um produto custa 80 e sobe 10%, passa a custar:", "84", "86", "88", "90", 3, "Dez por cento de 80 e 8."),
    QQ("A derivada de x^2 e:", "x", "2x", "x^3", "2", 2, "Regra da potencia."),
    QQ("O grafico de y = 5 e:", "Uma reta horizontal", "Uma reta vertical", "Uma parabola", "Um circulo", 1, "y nao muda."),
    QQ("Se 4x = 4, entao x vale:", "0", "1", "2", "4", 2, "Divida por 4."),

    QQ("Um baralho padrao sem coringas tem quantas cartas?", "48", "50", "52", "54", 3, "Sao 4 naipes com 13 cartas."),
    QQ("Quantos naipes existem em um baralho padrao?", "2", "3", "4", "5", 3, "Copas, Ouros, Espadas e Paus."),
    QQ("Quantas cartas ha em cada naipe?", "10", "12", "13", "14", 3, "Vai do As ao Rei."),
    QQ("Em poker, um Par significa:", "Duas cartas do mesmo naipe", "Duas cartas do mesmo valor", "Tres cartas iguais", "Cinco cartas em ordem", 2, "Exemplo: dois 7."),
    QQ("Em poker, Flush e:", "Cinco cartas em ordem", "Cinco cartas do mesmo naipe", "Tres cartas iguais", "Quatro cartas iguais", 2, "Nao exige sequencia."),
    QQ("Em poker, Straight e:", "Cinco cartas em ordem", "Cinco cartas do mesmo naipe", "Um par e uma trinca", "Quatro cartas do mesmo valor", 1, "A ordem importa."),
    QQ("Full House e formado por:", "Dois pares", "Uma trinca e um par", "Quatro cartas iguais", "Cinco cartas do mesmo naipe", 2, "3 + 2."),
    QQ("Quadra significa:", "Quatro cartas do mesmo valor", "Quatro cartas do mesmo naipe", "Duas duplas", "Quatro cartas em ordem", 1, "Exemplo: quatro reis."),
    QQ("Straight Flush combina:", "Ordem e mesmo naipe", "Dois pares e naipe igual", "Trinca e carta alta", "Quatro cartas iguais e uma extra", 1, "E uma sequencia no mesmo naipe."),
    QQ("O As costuma ser a carta de valor mais alto em muitos jogos?", "Sim", "Nao", "Somente em baralho espanhol", "Nunca", 1, "Em muitos jogos, sim."),
    QQ("Em um baralho padrao, Copas e Ouros sao naipes de qual cor?", "Azul", "Verde", "Vermelha", "Preta", 3, "Sao os naipes quentes."),
    QQ("Espadas e Paus sao naipes de qual cor?", "Branca", "Preta", "Vermelha", "Roxa", 2, "Sao os naipes escuros."),
    QQ("Em Blackjack, o objetivo classico e chegar perto de:", "15", "18", "21", "24", 3, "Numero bem famoso."),
    QQ("Em muitos jogos, embaralhar serve para:", "Ordenar o baralho", "Aleatorizar a ordem", "Dobrar a aposta", "Remover cartas", 2, "Evita previsibilidade."),
    QQ("Qual carta costuma ter valor 11 em Blackjack quando conveniente?", "2", "8", "Valete", "As", 4, "Ela pode valer 1 ou 11."),
    QQ("Descartar cartas significa:", "Misturar o baralho", "Remover cartas da mao para outra pilha", "Comprar duas cartas", "Trocar de naipe", 2, "Vai para a pilha de descarte."),
    QQ("Em truco, a palavra 'mao' geralmente se refere a:", "Um baralho novo", "As cartas em posse do jogador", "Uma aposta fixa", "O coringa", 2, "E o conjunto que voce segura."),
    QQ("Um coringa em muitos jogos funciona como:", "Carta inutil", "Carta especial de substituicao", "Carta mais fraca", "Apenas marcador", 2, "Pode assumir outros valores."),
    QQ("Um jogador que compra carta do topo do baralho esta:", "Descartando", "Blefando", "Puxando carta", "Fechando a rodada", 3, "Tambem se diz comprar."),
    QQ("Em poker, duas cartas de mesmo valor mais outras duas de outro valor formam:", "Par", "Dois pares", "Trinca", "Flush", 2, "Sao duas duplas."),
    QQ("Um baralho com coringas costuma ter quantas cartas?", "50", "52", "54", "56", 3, "Sao 52 mais 2 extras."),
    QQ("O dealer em um jogo de cartas e quem:", "Conta pontos", "Distribui cartas", "Ganha sempre", "Escolhe o naipe", 2, "Ele serve a mesa."),
    QQ("No poker, carta alta e usada quando:", "Nao ha combinacao melhor", "Ha um flush", "Ha uma quadra", "Ha um full house", 1, "E a menor categoria de mao."),
    QQ("Se cinco cartas tem o mesmo naipe mas nao estao em ordem, isso e:", "Straight", "Flush", "Full House", "Trinca", 2, "Mesmo naipe basta."),
    QQ("Em um jogo com 4 jogadores, distribuir uma carta para cada um por rodada e chamado de:", "Blefar", "Dar a volta", "Queimar carta", "Cortar o baralho", 2, "A carta passa pela mesa."),

    QQ("Qual e um sinonimo menos comum de 'bonito'?", "Formoso", "Rijido", "Avaro", "Lugubre", 1, "E usado em textos literarios."),
    QQ("Qual e um sinonimo menos comum de 'calmo'?", "Placido", "Aspero", "Arisco", "Mordaz", 1, "Traz ideia de serenidade."),
    QQ("Qual e um sinonimo menos comum de 'rapido'?", "Celere", "Taciturno", "Moroso", "Futil", 1, "Tambem aparece como 'celeridade'."),
    QQ("Qual e um sinonimo menos comum de 'antigo'?", "Vetusto", "Tenro", "Prolixo", "Hirsuto", 1, "Sugere algo muito velho."),
    QQ("Qual e um sinonimo menos comum de 'ajuda'?", "Arrimo", "Desvelo", "Tino", "Estorvo", 1, "Pode significar amparo."),
    QQ("Qual e um sinonimo menos comum de 'alegre'?", "Jovial", "Tacanho", "Soturno", "Inerte", 1, "Tem clima leve."),
    QQ("Qual e um sinonimo menos comum de 'triste'?", "Lacrimoso", "Ledo", "Arguto", "Farto", 1, "Relaciona-se a lagrimas."),
    QQ("Qual e um sinonimo menos comum de 'medo'?", "Temor", "Louvor", "Relevo", "Amago", 1, "A palavra aparece em expressoes formais."),
    QQ("Qual e um sinonimo menos comum de 'forca'?", "Vigor", "Tedio", "Fissura", "Parcela", 1, "Tambem e energia fisica."),
    QQ("Qual e um sinonimo menos comum de 'fala'?", "Locucao", "Miragem", "Sina", "Querela", 1, "Relaciona-se a expressao verbal."),
    QQ("Qual e um sinonimo menos comum de 'casa'?", "Lar", "Lide", "Vaga", "Lida", 1, "Palavra afetiva."),
    QQ("Qual e um sinonimo menos comum de 'caminho'?", "Vereda", "Maestria", "Tensao", "Rixa", 1, "Muito usado para trilhas."),
    QQ("Qual e um sinonimo menos comum de 'cheiro'?", "Aroma", "Estio", "Brio", "Lavor", 1, "Pode ser agradavel."),
    QQ("Qual e um sinonimo menos comum de 'raiva'?", "Colera", "Candura", "Placidez", "Ardil", 1, "Tambem e nome de doenca, mas aqui e emocao."),
    QQ("Qual e um sinonimo menos comum de 'leve'?", "Ligeiro", "Gravoso", "Taciturno", "Perecivel", 1, "Tambem pode indicar rapidez."),
    QQ("Qual e um sinonimo menos comum de 'duvida'?", "Hesitacao", "Jubilo", "Fastio", "Feito", 1, "Tem relacao com indecisao."),
    QQ("Qual e um sinonimo menos comum de 'barulho'?", "Alarido", "Amago", "Nexa", "Nuvem", 1, "Parece algo escandaloso."),
    QQ("Qual e um sinonimo menos comum de 'brilho'?", "Fulgor", "Torpor", "Lacuna", "Avido", 1, "Muito usado em poesia."),
    QQ("Qual e um sinonimo menos comum de 'fome'?", "Inedia", "Melopeia", "Brandura", "Nobreza", 1, "E um termo formal."),
    QQ("Qual e um sinonimo menos comum de 'sono'?", "Modorra", "Alvoroco", "Apendice", "Vereda", 1, "Da ideia de sonolencia."),
    QQ("Qual e um sinonimo menos comum de 'cuidado'?", "Zelo", "Arruaça", "Falacia", "Traje", 1, "Tambem pode ser atençao."),
    QQ("Qual e um sinonimo menos comum de 'engano'?", "Equivoco", "Remanso", "Candura", "Pudor", 1, "Erro de avaliacao."),
    QQ("Qual e um sinonimo menos comum de 'amizade'?", "Camaradagem", "Acrimonia", "Cizania", "Penuria", 1, "Termo de convivencia amistosa."),
    QQ("Qual e um sinonimo menos comum de 'trabalho'?", "Labuta", "Melopeia", "Apendice", "Sutileza", 1, "Sugere esforco continuo."),
    QQ("Qual e um sinonimo menos comum de 'grande'?", "Vasto", "Parco", "Raso", "Mudo", 1, "Pode indicar ampla extensao.")
};

static const QuizQuestion QUIZ_HARD_QUESTIONS[] = {
    QQ("Em C, qual expressao acessa o valor apontado por um ponteiro p?", "&p", "*p", "p&", "p*", 2, "O operador tambem aparece em multiplicacao."),
    QQ("Qual problema ocorre ao usar gets?", "Ela nao le espacos", "Nao controla tamanho do buffer", "Ela le somente numeros", "Ela fecha o arquivo", 2, "O risco e de estouro."),
    QQ("Qual cabecalho declara malloc e free?", "string.h", "math.h", "stdlib.h", "time.h", 3, "Memoria dinamica mora nele."),
    QQ("Se int x = 5; int *p = &x; (*p)++; quanto vale x?", "4", "5", "6", "7", 3, "O ponteiro altera x diretamente."),
    QQ("Qual afirmacao sobre arrays em C e correta?", "Sabem seu tamanho em qualquer funcao", "Decaem para ponteiro ao serem passados para funcao", "Nunca podem ser percorridos com for", "Nao podem guardar char", 2, "O nome do array vira endereco no parametro."),
    QQ("Qual e o caso-base de uma recursao?", "A chamada mais demorada", "A condicao que encerra as chamadas", "O primeiro include", "Um ponteiro nulo", 2, "Sem ele a recursao nao para."),
    QQ("Em C, qual operador tem precedencia maior em a + b * c?", "+", "*", "=", "&&", 2, "Multiplicacao vem antes."),
    QQ("Qual instrucao seleciona caminhos por varios valores inteiros?", "while", "switch", "union", "extern", 2, "Usa case."),
    QQ("Qual e o resultado de 7 / 2 com ambos operandos int?", "3", "3.5", "4", "2.5", 1, "Divisao inteira descarta a fracao."),
    QQ("O que faz realloc?", "Sempre zera a memoria", "Muda o tamanho de um bloco alocado", "Converte int em float", "Fecha um arquivo", 2, "Pode crescer ou encolher um bloco."),
    QQ("Qual funcao compara strings por conteudo?", "strlen", "strcmp", "strcpy", "fputs", 2, "Ela retorna 0 quando sao iguais."),
    QQ("Qual e o risco de esquecer free apos malloc em loops longos?", "Stack overflow", "Memory leak", "Erro de sintaxe", "Loop infinito", 2, "A memoria fica ocupada."),
    QQ("Qual operador verifica se dois valores sao diferentes?", "==", "!=", "<=", "++", 2, "Tem um ponto de exclamacao."),
    QQ("Se um arquivo e aberto com modo \"a\", o que acontece?", "O conteudo e apagado", "O ponteiro inicia no fim para anexar", "So leitura e permitida", "O arquivo vira binario", 2, "Serve para acrescentar."),
    QQ("Qual afirmacao sobre scanf(\"%d\", &x) esta correta?", "O & entrega o endereco de x", "O & converte x em float", "O %d le string", "scanf devolve void", 1, "scanf precisa saber onde gravar."),
    QQ("Qual estrutura de dados e mais natural para LIFO?", "Fila", "Pilha", "Arvore binaria", "Grafo completo", 2, "Ultimo que entra, primeiro que sai."),
    QQ("Qual funcao mede o comprimento de uma string sem contar o '\\0'?", "sizeof", "strlen", "strchr", "atoi", 2, "Retorna quantidade de caracteres uteis."),
    QQ("Se int v[4] = {2,4,6,8}; qual e v[2]?", "2", "4", "6", "8", 3, "Arrays em C comecam no indice 0."),
    QQ("Qual palavra-chave evita que uma variavel local seja recriada a cada chamada?", "volatile", "signed", "static", "typedef", 3, "Ela preserva o valor entre chamadas."),
    QQ("Qual e a principal diferenca entre struct e typedef struct?", "Nenhuma diferenca de sintaxe existe", "typedef cria um alias para o tipo", "struct so guarda ints", "typedef libera memoria", 2, "Ajuda a evitar repetir struct Nome."),
    QQ("Qual operacao faz curto-circuito logico em C?", "&& e ||", "% e /", "+ e -", "<< e >>", 1, "Pode evitar avaliar a segunda expressao."),
    QQ("Em ponteiros, p + 1 avanca:", "1 byte sempre", "1 unidade do tipo apontado", "1 bit", "Ate o fim da memoria", 2, "Depende do tipo do ponteiro."),
    QQ("O que EOF costuma indicar ao ler arquivos?", "Fim de arquivo", "Arquivo aberto", "Erro de compilacao", "Memoria livre", 1, "A leitura terminou."),
    QQ("Qual e a saida de printf(\"%d\", (3 > 2) && (2 > 1));?", "0", "1", "2", "3", 2, "As duas comparacoes sao verdadeiras."),
    QQ("Quando passamos uma struct grande por valor para funcao, geralmente:", "Nada e copiado", "Uma copia e criada", "Ela vira array", "Ela e desalocada", 2, "Pode custar mais memoria e tempo."),

    QQ("Se f(x) = x^2 - 5x + 6, quais sao as raizes?", "1 e 6", "2 e 3", "3 e 4", "2 e 6", 2, "Fatore a expressao."),
    QQ("A solucao de 3x - 7 >= 11 e:", "x >= 6", "x >= 5", "x <= 6", "x <= 5", 1, "Some 7 e divida por 3."),
    QQ("Se g(x) = 2x - 1, qual e g^-1(x)?", "(x - 1)/2", "(x + 1)/2", "2x + 1", "1 - 2x", 2, "Troque x por y e isole."),
    QQ("Qual e o vertice da parabola y = x^2 - 4x + 3?", "(2,-1)", "(2,1)", "(4,-3)", "(-2,1)", 1, "Use -b/2a."),
    QQ("A derivada de 3x^2 + 2x - 5 e:", "6x + 2", "3x + 2", "6x - 5", "2x + 3", 1, "Derive termo a termo."),
    QQ("A integral indefinida de 2x dx e:", "x^2 + C", "2x + C", "x + C", "x^3 + C", 1, "E a operacao inversa da derivada."),
    QQ("Se logica: p e verdadeira e q e falsa, qual e p && q?", "Verdadeiro", "Falso", "Indefinido", "Depende de r", 2, "Ambas precisam ser verdadeiras."),
    QQ("Se um triangulo retangulo tem catetos 6 e 8, a hipotenusa e:", "9", "10", "11", "12", 2, "Teorema de Pitagoras."),
    QQ("A soma das raizes de x^2 - 7x + 10 = 0 e:", "5", "7", "10", "12", 2, "Use -b/a."),
    QQ("Se 2^(x) = 32, quanto vale x?", "4", "5", "6", "7", 2, "Pense nas potencias de 2."),
    QQ("A funcao y = -x^2 + 4 e concava para:", "Cima", "Baixo", "Ambos", "Nenhum", 2, "O coeficiente de x^2 e negativo."),
    QQ("Se h(x) = 1/x, qual e h(1/2)?", "1/4", "1/2", "2", "4", 3, "Dividir por meio equivale a multiplicar por 2."),
    QQ("Qual e o dominio real de f(x) = 1/(x - 3)?", "Todos os reais", "Todos os reais exceto 0", "Todos os reais exceto 3", "Somente x > 3", 3, "O denominador nao pode zerar."),
    QQ("Se uma PA tem a1 = 4 e razao 3, qual e a4?", "10", "11", "12", "13", 4, "Some a razao tres vezes."),
    QQ("A media ponderada de 7 e 9 com pesos 1 e 3 e:", "8", "8.5", "8.75", "9", 3, "Peso maior puxa a media para 9."),
    QQ("Se x^2 = 49, quais solucoes reais existem?", "Somente 7", "Somente -7", "7 e -7", "Nenhuma", 3, "Quadrado de positivo e negativo pode coincidir."),
    QQ("Qual e a imagem de x = -1 na funcao y = x^3?", "-3", "-1", "1", "3", 2, "Numero negativo elevado a expoente impar continua negativo."),
    QQ("Em inequacoes, ao multiplicar ambos os lados por numero negativo, o sinal:", "Permanece igual", "Inverte", "Vira igualdade", "Some", 2, "Regra classica."),
    QQ("Se sen^2 t + cos^2 t =", "0", "1", "2", "Depende de t", 2, "Identidade fundamental."),
    QQ("O coeficiente angular da reta y = -3x + 8 e:", "-3", "3", "8", "-8", 1, "E o numero que acompanha x."),
    QQ("Em uma PG com a1=2 e razao=3, qual e a3?", "6", "9", "18", "27", 3, "Multiplique pela razao duas vezes."),
    QQ("A derivada de uma constante e:", "0", "1", "A propria constante", "x", 1, "Nao varia."),
    QQ("Se f(x)=|x|, quanto vale f(-7)?", "-7", "0", "7", "14", 3, "Valor absoluto nao guarda sinal."),
    QQ("O sistema x+y=10 e x-y=2 tem solucao:", "(6,4)", "(4,6)", "(5,5)", "(8,2)", 1, "Some as equacoes."),
    QQ("Se o discriminante de uma quadratica e negativo, as raizes reais sao:", "Duas e distintas", "Iguais", "Inexistentes", "Sempre inteiras", 3, "Nao corta o eixo x."),
    QQ("A taxa percentual equivalente a multiplicar por 1,25 e:", "12,5%", "20%", "25%", "125%", 3, "Existe acréscimo de um quarto."),

    QQ("Em poker tradicional, qual mao vence um Full House?", "Flush", "Straight", "Quadra", "Dois Pares", 3, "Quatro cartas iguais superam 3+2."),
    QQ("Quantas combinacoes de 5 cartas podem ser feitas a partir de 52 cartas, sem ordem?", "2.598.960", "311.875.200", "270.725", "52^5", 1, "E o famoso numero de maos de poker."),
    QQ("Qual a probabilidade aproximada de sair um As em uma compra unica de 52 cartas?", "1/4", "1/13", "1/26", "4/13", 2, "Ha 4 ases no baralho."),
    QQ("No Texas Hold'em, quantas cartas comunitarias podem aparecer ao final?", "3", "4", "5", "6", 3, "Flop, turn e river."),
    QQ("Qual dessas maos e mais forte em poker?", "Straight", "Flush", "Full House", "Quadra", 4, "Apenas uma perde para ela entre essas."),
    QQ("Se duas maos de poker sao do mesmo tipo, o desempate costuma usar:", "A cor da carta", "O valor das cartas relevantes", "Quem falou primeiro", "O naipe de copas", 2, "Compara-se o peso das cartas."),
    QQ("Um Royal Flush e:", "A, K, Q, J, 10 do mesmo naipe", "Cinco ases", "Cinco cartas vermelhas", "Uma quadra com As", 1, "E a melhor mao classica."),
    QQ("Qual desses jogos usa exatamente 4 jogadores em sua forma classica de parceria?", "Blackjack", "Bridge", "Paciência", "Buraco fechado para 2", 2, "Joga-se em duplas."),
    QQ("Em blackjack, se voce estoura 21, o nome comum disso e:", "Stand", "Split", "Bust", "Blind", 3, "Voce passou do limite."),
    QQ("Em truco paulista, qual manilha varia conforme a vira?", "Manilha velha", "Manilha fixa", "Manilha movel", "Carta baixa", 3, "Ela muda a cada rodada."),
    QQ("Se 5 jogadores recebem 5 cartas cada de um baralho de 52, quantas cartas sobram?", "22", "25", "27", "32", 3, "Foram distribuidas 25."),
    QQ("Qual e a quantidade de reis em um baralho comum?", "2", "3", "4", "5", 3, "Um por naipe."),
    QQ("Em um jogo de vazas, vencer a vaza geralmente significa:", "Ganhar as cartas da rodada jogada", "Comprar duas cartas extras", "Trocar de parceiro", "Encerrar a partida", 1, "A mesa e recolhida pelo vencedor."),
    QQ("Em poker, kicker e:", "Carta extra usada no desempate", "Carta comunitaria virada de lado", "Carta descartada pelo dealer", "Carta que vale zero", 1, "Desempata pares e afins."),
    QQ("Se uma mao tem A, 2, 3, 4, 5 em sequencia, isso pode valer como:", "Straight baixo", "Flush obrigatorio", "Full House", "Quadra", 1, "O As pode ser baixo em alguns casos."),
    QQ("Quantos ases podem aparecer, no maximo, em uma mao de 5 cartas de um baralho comum?", "2", "3", "4", "5", 3, "Existe um por naipe."),
    QQ("Em jogos com coringa como substituto, ele costuma ser considerado:", "Carta selvagem", "Carta neutra sem funcao", "Carta bloqueada", "Carta apenas decorativa", 1, "Substitui outras."),
    QQ("No poker aberto, o que significa blefar?", "Mostrar as cartas cedo", "Fingir uma mao forte ou fraca", "Comprar do descarte", "Reembaralhar", 2, "E um jogo de leitura."),
    QQ("Em Blackjack, separar um par inicial em duas maos chama-se:", "Hit", "Split", "Fold", "Draw", 2, "Cada carta igual vira o inicio de uma mao."),
    QQ("Se um jogo distribui 7 cartas para cada um de 4 jogadores com 52 cartas, sobram:", "20", "22", "24", "26", 3, "Foram 28 distribuidas."),
    QQ("Em poker, uma mao com tres cartas iguais e duas cartas desconexas e:", "Trinca", "Full House", "Dois Pares", "Straight", 1, "Falta um par para o full house."),
    QQ("Qual das opcoes abaixo NAO e um naipe do baralho frances?", "Copas", "Ouros", "Espadas", "Cetros", 4, "Nao existe no baralho comum."),
    QQ("Quando duas maos tem o mesmo Straight, o resultado usual e:", "Ganha quem tem copas", "Empate", "Ganha o dealer", "Reembaralha", 2, "As sequencias sao equivalentes."),
    QQ("Em jogos de compra e descarte, manter cartas conectadas do mesmo naipe geralmente ajuda a buscar:", "Flush ou straight", "Apenas carta alta", "Somente manilhas", "Nenhuma combinacao", 1, "Abre caminho para maos melhores."),
    QQ("Em um baralho sem coringas, a chance de tirar uma carta vermelha em uma compra e:", "1/4", "1/3", "1/2", "2/3", 3, "Metade do baralho e vermelha."),

    QQ("Qual e um sinonimo mais erudito de 'breve'?", "Efemero", "Colossal", "Taciturno", "Probido", 1, "Dura pouco."),
    QQ("Qual e um sinonimo mais erudito de 'duro' no sentido de severo?", "Acerbo", "Ludico", "Lasso", "Rutilo", 1, "Tambem pode significar amargo."),
    QQ("Qual e um sinonimo mais erudito de 'preguica'?", "Lassidao", "Tenacidade", "Fulgor", "Candura", 1, "Traz ideia de moleza."),
    QQ("Qual e um sinonimo mais erudito de 'orgulho exagerado'?", "Soberba", "Brandura", "Laconismo", "Melopeia", 1, "Peca capital."),
    QQ("Qual e um sinonimo mais erudito de 'confusao'?", "Emaranhado", "Plenitude", "Desvelo", "Alvura", 1, "Algo intrincado."),
    QQ("Qual e um sinonimo mais erudito de 'silencio'?", "Taciturnidade", "Rumor", "Estridor", "Acrimonia", 1, "Relaciona-se a ficar calado."),
    QQ("Qual e um sinonimo mais erudito de 'frio' no sentido emocional?", "Glacial", "Rutilante", "Prisco", "Mordaz", 1, "Parece gelo."),
    QQ("Qual e um sinonimo mais erudito de 'sabedoria'?", "Sapiência", "Molicia", "Frivolidade", "Empafia", 1, "Forma culta bastante usada."),
    QQ("Qual e um sinonimo mais erudito de 'erro pequeno'?", "Lapso", "Fastio", "Hegemonia", "Bravata", 1, "Pode ser de memoria."),
    QQ("Qual e um sinonimo mais erudito de 'vontade intensa'?", "Avididade", "Pusilanimidade", "Laxismo", "Parcimonia", 1, "Desejo forte."),
    QQ("Qual e um sinonimo mais erudito de 'amparo'?", "Esteio", "Calunia", "Estorvo", "Melopeia", 1, "Aquilo que sustenta."),
    QQ("Qual e um sinonimo mais erudito de 'clareza'?", "Nitidez", "Lascivia", "Penuria", "Insania", 1, "Algo bem definido."),
    QQ("Qual e um sinonimo mais erudito de 'cansaço'?", "Fatigacao", "Diletancia", "Temeridade", "Placidez", 1, "Ligado a fadiga."),
    QQ("Qual e um sinonimo mais erudito de 'desordem'?", "Balburdia", "Plenitude", "Lenitivo", "Tino", 1, "Muito usado em debates."),
    QQ("Qual e um sinonimo mais erudito de 'remedio' no sentido de alivio?", "Lenitivo", "Laconismo", "Acrasia", "Vituperio", 1, "Serve para suavizar."),
    QQ("Qual e um sinonimo mais erudito de 'pouco'?", "Parco", "Vasto", "Opimo", "Hirto", 1, "O oposto de abundante."),
    QQ("Qual e um sinonimo mais erudito de 'abundante'?", "Opimo", "Parco", "Exiguo", "Tacanho", 1, "Muito rico ou farto."),
    QQ("Qual e um sinonimo mais erudito de 'corajoso'?", "Intrépido", "Moroso", "Pusilanime", "Lasso", 1, "Nao teme facilmente."),
    QQ("Qual e um sinonimo mais erudito de 'medroso'?", "Pusilanime", "Altivo", "Proficuo", "Sublime", 1, "Falta-lhe coragem."),
    QQ("Qual e um sinonimo mais erudito de 'discurso longo e cansativo'?", "Prolixidade", "Candura", "Argucia", "Pujança", 1, "Excesso de palavras."),
    QQ("Qual e um sinonimo mais erudito de 'esperteza'?", "Argucia", "Apatia", "Languidez", "Penuria", 1, "Inteligencia afiada."),
    QQ("Qual e um sinonimo mais erudito de 'fraqueza moral'?", "Acrasia", "Resiliencia", "Pujanca", "Jovialidade", 1, "Falta de dominio de si."),
    QQ("Qual e um sinonimo mais erudito de 'insulto severo'?", "Vituperio", "Esteio", "Candura", "Sapiência", 1, "Palavra de reprovação."),
    QQ("Qual e um sinonimo mais erudito de 'insanidade'?", "Desvario", "Fidalguia", "Parcimonia", "Diletancia", 1, "Perda de juizo."),
    QQ("Qual e um sinonimo mais erudito de 'economia excessiva'?", "Parcimonia", "Pujanca", "Opulencia", "Diligencia", 1, "Contencao extrema.")
};

#undef QQ

static inline const QuizQuestion *quiz_question_pool(int hard_mode, int *count) {
    if (hard_mode) {
        if (count) *count = (int)(sizeof(QUIZ_HARD_QUESTIONS) / sizeof(QUIZ_HARD_QUESTIONS[0]));
        return QUIZ_HARD_QUESTIONS;
    }
    if (count) *count = (int)(sizeof(QUIZ_EASY_QUESTIONS) / sizeof(QUIZ_EASY_QUESTIONS[0]));
    return QUIZ_EASY_QUESTIONS;
}

#endif
